### PR TITLE
Updated peer dependencies to include React >= 0.12

### PR DESCRIPTION
**Pull request by poteto**

### CODE REVIEW

**Comment by lencioni** [comment]
Thanks for the PR! Nothing comes to mind about React 0.13 that would prevent this from working there, but I haven't actually tried it out yet. Have you tried using react-waypoint with React 0.13 yet?

**Comment by lencioni** [comment]
Also, I'm a little bit nervous about opting in to all future versions of React, but maybe it's not a big deal. Can you point to some other projects that do this?

**Comment by poteto** [comment]
I'm in the process of updating our [production app](http://www.homely.com.au) to React `0.13.1`, and so far I haven't encountered any issues with react-waypoint in dev. Would you prefer if I be more explicit about versions, i.e. `~0.13.x`?

**Comment by lencioni** [comment]
> I'm in the process of updating our production app to React 0.13.1, and so far I haven't encountered any issues with react-waypoint in dev.

Awesome! I figured as much but thought it would be best to make sure just in case. In the future, it might be nice to mention details like that in the commit message.

> Would you prefer if I be more explicit about versions, i.e. ~0.13.x?

At least for now, I think that would be best.

**Comment by poteto** [comment]
@lencioni Rebased! Thanks for this component :)

**Pull request merged**
