### PR TITLE
Add React 15.0 support

### PR DESCRIPTION
**Pull request by kamui**
Related to: https://github.com/brigade/react-waypoint/issues/74

### CODE REVIEW

**Comment by trotzig** [comment]
Thanks! Would you mind bumping the dev dependencies to 15.0 as well? See #74 for some more context.

**Comment by kamui** [comment]
Oops, updated that too.

**Comment by trotzig** [comment]
Sorry for the back-and-forth, but could you change so that the devDependency is ^15.0.0 only? That would make dev and our tests more predictable since we're moving away from 0.14 anyway. There is of course a risk that we add funcionality that's not compatible with 0.14, but let's worry about that then.

**Comment by kamui** [comment]
No problem, the dev deps only are now ^15.

**Comment by trotzig** [comment]
Thanks for the quick turnaround! I'll merge this and push a new version later tonight (in a few hours).

**Comment by kamui** [comment]
Great, thanks! This was the last module in my app that was locked to 0.14.

**Pull request merged**
