### PR TITLE
Let prop types be removable in consumers production bundles

### PR DESCRIPTION
**Pull request by Andarist**

### CODE REVIEW

**Comment by jmeas** [comment]
Thanks for the PR! The description makes this seem like a good change, but I’ll need to do more research before I can give this a thumbs up or down.

I appreciate these PRs, @andarist!

**Comment by Andarist** [comment]
Sure thing. If you have any questions, just ask :) To see the actual impact on the codebase I'd suggest building `master` and my branch and seeing the diff between them.

**Comment by lencioni** [comment]
Although I love the intention here, I worry a bit about this breaking
folks. We should make sure that the proptypes are a named export to people
have a path forward if they need the proptypes for some reason.

**Comment by Andarist** [comment]
Hm, yeah that could be done probably, although maybe better to export them if requested by the community and not before?

**Comment by lencioni** [comment]
Yeah that might be alright too

**Comment by trotzig** [comment]
I'm 👍 this change as well.

**Pull request merged**
