### PR TITLE
Update to support React 16

### LINKED ISSUE #213: Support React 16
Probably nothing has to change but you'll need to update peerDependencies

### PR DESCRIPTION
**Pull request by jmeas**
Will resolve #213 

---

Note: Travis CI will fail because React 16 isn't out yet. But, once it is out, we can restart the build and this _should_ work.

Also, we can close this PR out and just keep the branch around if we don't want to wait to have this PR hanging around. But it sounds like 16 should be released soon.

### CODE REVIEW

**Comment by lencioni** [comment]
I restarted the tests, but it looks like they don't pass. I won't have time to look at this today--do one of you have the bandwidth?

**Comment by jmeas** [comment]
A quick look suggests that it's related to the tests involving errors. I haven't looked too much into how React 16's error boundaries affect errors being thrown, but we may need to update the way that we're testing the current behavior?

I'm at an offsite today, so I also won't have time to investigate further

**Comment by lencioni** [comment]
I'm working on this right now.

**Comment by lencioni** [comment]
@gribnoysup in 7416759 I disabled a test you added to unblock the React 16 update. Once this is merged, do you think you could look into re-enabling this test in a way that passes in React 14, 15, and 16?

**Comment by gribnoysup** [comment]
@lencioni yes, sure!

**Comment by trotzig** [comment]
Thanks all!

**Pull request merged**
