### PR TITLE
fix document and html detection. Previous solution does not work well with iframe

### PR DESCRIPTION
**Pull request by petrbrzek**

### CODE REVIEW

**Comment by lencioni** [comment]
Thanks for the pull request! Would you please add a test that reproduces the issue to prevent regressions?

**Comment by petrbrzek** [comment]
Sorry it was probably false positive. I've tested previous solution in my app today and no bug happened. So it's probably safe to close it.

**Comment by lencioni** [comment]
Alright, thanks for looping back!

**Comment by petrbrzek** [comment]
Ok, it is a real problem but I'm unable to reproduce it every time (the pull request fixes it because of better document detection). Here is the screenshot. 

avocode_-_2_4_5__dev_mode_

**Comment by petrbrzek** [comment]
We should probably reopen this one @lencioni.

**Pull request closed without merging**
