### PR TITLE
Add direction specific functions

### PR DESCRIPTION
**Pull request by nickclaw**
This adds 4 more optional properties to the Waypoint component: `onEnterFromAbove`, `onEnterFromBelow`, `onLeaveToAbove`, `onLeaveToBelow`.

I haven't updated any tests yet, so don't merge this yet. I just want to make sure this is something that could be accepted before I put too much time into it :)

### CODE REVIEW

**Comment by nickclaw** [comment]
Could close #25

**Comment by trotzig** [comment]
Hi @nickclaw, and thanks for contributing to react-waypoint!

This looks useful, but it would be good to understand the usecase a little better. 

Instead of adding the new props, what do you think about passing the previous and current position to the callbacks? We would have to combine it with the native event thats being passed in, but how about something like this

onLeave({ previousPosition: 'inside', currentPosition: 'below', nativeEvent: event});

**Comment by lencioni** [comment]
Another option would be to pass direction or edge to the `onEnter` and `onLeave` callbacks. Something like:

```js
onLeave(event, 'bottom')
```

**Comment by nickclaw** [comment]
@trotzig My use case is something like Apple Calendar, where I have a Waypoint component next to each month, when the Waypoint leaves from the top I want to change the fixed title, and when it enters from the top I want to revert the title to the previous month.

screen



@lencioni that was what I initially tried, but I didn't like the inconsistency between the meaning of the second parameter between the two functions.

```
onLeave(event, currentLocation)
onEnter(event, previousLocation)
```

I think my solution is easier on users because they can just declare what specific events they want to be notified about, instead of having to compare string constants to figure out what's going on. But I can see why adding a property for every possibility isn't as scalable if this module ever handles horizontal scrolling.

What do you guys think? I wouldn't mind changing my pull request to match @lencioni's solution :)

**Comment by trotzig** [comment]
Thanks for the use case description and the gif (that looks great by the way!), it helps us to understand the problem better. I like @lencioni's suggestion in that it doesn't break backwards compatibility with the native `event` being passed down. 

I think it's okay for consumers to have to compare strings for this type of use case. So I'd say go with what @lencioni said. It would be great if you could add a test for this. And make sure to add your use case to the commit message, some documentation to README.md, plus a short description in CHANGELOG.md.

**Comment by nickclaw** [comment]
Alright feeling pretty good about the state of the pull request. I didn't update `package.json`, but I figure this is a minor version bump.

**Comment by trotzig** [comment]
Thanks @nickclaw!

also: lol, I just realized that gif is from the actual Apple Calendar... It would be fun to see your implementation though!

**Comment by trotzig** [comment]
I'll cut a new release in a few hours, got to run out now.

**Pull request merged**
