### PR TITLE
Update tests to jsx

### PR DESCRIPTION
**Pull request by gribnoysup**
As we discussed in https://github.com/brigade/react-waypoint/pull/208#discussion_r135766047 I updated tests to use `JSX` syntax instead of `React.createElement` 

I'm not sure about the `.projections.json` as I am not a vim user, but I tested it and `:A` seems to work fine with this config in all files (but maybe there is a more elegant way to do this)

### CODE REVIEW

**Comment by trotzig** [comment]
Great, thanks! I gave the .projections.json changes a test in vim and it works. Before we merge however, can you update CONTRIBUTING.md, I believe there's at least one reference to the old spec folder there.

**Comment by gribnoysup** [comment]
Oops, sorry, missed that one!

**Comment by gribnoysup** [comment]
Any other changes you want me to make before merging? :)

**Comment by trotzig** [comment]
Sorry, I thought I already merged!

**Comment by gribnoysup** [comment]
No problem! I thought I missed something :D

**Pull request merged**
